env:
  es2020: true
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

plugins:
  - jest

# Включает поддержку конструкции import.meta.url
parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант